executor: "KubernetesExecutor"
images:
  airflow:
    extraPipPackages:  # Add this section under `images.airflow`
      - apache-airflow-providers-amazon==8.28.0
      - boto3
dags:
  persistence:
    # Annotations for dags PVC
    annotations: {}
    # Enable persistent volume for storing dags
    enabled: false
    # Volume size for dags
    size: 1Gi
    # If using a custom storageClass, pass name here
    storageClassName:
    # access mode of the persistent volume
    accessMode: ReadWriteOnce
    ## the name of an existing PVC to use
    existingClaim:
    ## optional subpath for dag volume mount
    subPath: ~
  # GitSync configuration
  gitSync:
    enabled: true
    # Git repository URL
    repo: https://github.com/shadab-bigdel/airflow-helm-chart.git
    branch: main
    # The Git revision to check out (branch, tag, or hash)
    ref: main
    depth: 1
    # Maximum number of consecutive failures allowed before aborting
    maxFailures: 0
    # Subpath within the repo where DAGs are located
    # Should be "" if DAGs are at the repo root
    subPath: "dags"